package com.nf147.dao;

import com.nf147.entity.Inventories;
import java.util.List;

public interface InventoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer inventoriesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories
     *
     * @mbg.generated
     */
    int insert(Inventories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories
     *
     * @mbg.generated
     */
    Inventories selectByPrimaryKey(Integer inventoriesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories
     *
     * @mbg.generated
     */
    List<Inventories> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventories
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Inventories record);
}