package com.nf147.entity;

public class Apiresponse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiresponse.a_code
     *
     * @mbg.generated
     */
    private Integer aCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiresponse.a_type
     *
     * @mbg.generated
     */
    private String aType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiresponse.a_message
     *
     * @mbg.generated
     */
    private String aMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiresponse.a_code
     *
     * @return the value of apiresponse.a_code
     *
     * @mbg.generated
     */
    public Integer getaCode() {
        return aCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiresponse.a_code
     *
     * @param aCode the value for apiresponse.a_code
     *
     * @mbg.generated
     */
    public void setaCode(Integer aCode) {
        this.aCode = aCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiresponse.a_type
     *
     * @return the value of apiresponse.a_type
     *
     * @mbg.generated
     */
    public String getaType() {
        return aType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiresponse.a_type
     *
     * @param aType the value for apiresponse.a_type
     *
     * @mbg.generated
     */
    public void setaType(String aType) {
        this.aType = aType == null ? null : aType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiresponse.a_message
     *
     * @return the value of apiresponse.a_message
     *
     * @mbg.generated
     */
    public String getaMessage() {
        return aMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiresponse.a_message
     *
     * @param aMessage the value for apiresponse.a_message
     *
     * @mbg.generated
     */
    public void setaMessage(String aMessage) {
        this.aMessage = aMessage == null ? null : aMessage.trim();
    }
}