package com.nf147.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.c_id
     *
     * @return the value of category.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.c_id
     *
     * @param cId the value for category.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.c_name
     *
     * @return the value of category.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.c_name
     *
     * @param cName the value for category.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }
}