package com.nf147.entity;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_id
     *
     * @mbg.generated
     */
    private Integer oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_quantity
     *
     * @mbg.generated
     */
    private Integer oQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_shipDate
     *
     * @mbg.generated
     */
    private String oShipdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_status
     *
     * @mbg.generated
     */
    private String oStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_order
     *
     * @mbg.generated
     */
    private String oOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_id
     *
     * @return the value of orders.o_id
     *
     * @mbg.generated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_id
     *
     * @param oId the value for orders.o_id
     *
     * @mbg.generated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.p_id
     *
     * @return the value of orders.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.p_id
     *
     * @param pId the value for orders.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_quantity
     *
     * @return the value of orders.o_quantity
     *
     * @mbg.generated
     */
    public Integer getoQuantity() {
        return oQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_quantity
     *
     * @param oQuantity the value for orders.o_quantity
     *
     * @mbg.generated
     */
    public void setoQuantity(Integer oQuantity) {
        this.oQuantity = oQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_shipDate
     *
     * @return the value of orders.o_shipDate
     *
     * @mbg.generated
     */
    public String getoShipdate() {
        return oShipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_shipDate
     *
     * @param oShipdate the value for orders.o_shipDate
     *
     * @mbg.generated
     */
    public void setoShipdate(String oShipdate) {
        this.oShipdate = oShipdate == null ? null : oShipdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_status
     *
     * @return the value of orders.o_status
     *
     * @mbg.generated
     */
    public String getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_status
     *
     * @param oStatus the value for orders.o_status
     *
     * @mbg.generated
     */
    public void setoStatus(String oStatus) {
        this.oStatus = oStatus == null ? null : oStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.o_order
     *
     * @return the value of orders.o_order
     *
     * @mbg.generated
     */
    public String getoOrder() {
        return oOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.o_order
     *
     * @param oOrder the value for orders.o_order
     *
     * @mbg.generated
     */
    public void setoOrder(String oOrder) {
        this.oOrder = oOrder == null ? null : oOrder.trim();
    }
}