package com.nf147.entity;

public class Pet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.p_category
     *
     * @mbg.generated
     */
    private String pCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.p_photoUrls
     *
     * @mbg.generated
     */
    private String pPhotourls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.p_tags
     *
     * @mbg.generated
     */
    private String pTags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet.p_status
     *
     * @mbg.generated
     */
    private String pStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.p_id
     *
     * @return the value of pet.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.p_id
     *
     * @param pId the value for pet.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.p_category
     *
     * @return the value of pet.p_category
     *
     * @mbg.generated
     */
    public String getpCategory() {
        return pCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.p_category
     *
     * @param pCategory the value for pet.p_category
     *
     * @mbg.generated
     */
    public void setpCategory(String pCategory) {
        this.pCategory = pCategory == null ? null : pCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.p_name
     *
     * @return the value of pet.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.p_name
     *
     * @param pName the value for pet.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.p_photoUrls
     *
     * @return the value of pet.p_photoUrls
     *
     * @mbg.generated
     */
    public String getpPhotourls() {
        return pPhotourls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.p_photoUrls
     *
     * @param pPhotourls the value for pet.p_photoUrls
     *
     * @mbg.generated
     */
    public void setpPhotourls(String pPhotourls) {
        this.pPhotourls = pPhotourls == null ? null : pPhotourls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.p_tags
     *
     * @return the value of pet.p_tags
     *
     * @mbg.generated
     */
    public String getpTags() {
        return pTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.p_tags
     *
     * @param pTags the value for pet.p_tags
     *
     * @mbg.generated
     */
    public void setpTags(String pTags) {
        this.pTags = pTags == null ? null : pTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet.p_status
     *
     * @return the value of pet.p_status
     *
     * @mbg.generated
     */
    public String getpStatus() {
        return pStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet.p_status
     *
     * @param pStatus the value for pet.p_status
     *
     * @mbg.generated
     */
    public void setpStatus(String pStatus) {
        this.pStatus = pStatus == null ? null : pStatus.trim();
    }
}