package com.nf147.entity;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.t_id
     *
     * @mbg.generated
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.t_name
     *
     * @mbg.generated
     */
    private String tName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.t_id
     *
     * @return the value of tag.t_id
     *
     * @mbg.generated
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.t_id
     *
     * @param tId the value for tag.t_id
     *
     * @mbg.generated
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.t_name
     *
     * @return the value of tag.t_name
     *
     * @mbg.generated
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.t_name
     *
     * @param tName the value for tag.t_name
     *
     * @mbg.generated
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }
}