package com.nf147.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbg.generated
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_firstName
     *
     * @mbg.generated
     */
    private String uFirstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_lastName
     *
     * @mbg.generated
     */
    private String uLastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_email
     *
     * @mbg.generated
     */
    private String uEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbg.generated
     */
    private String uPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_phone
     *
     * @mbg.generated
     */
    private String uPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_Status
     *
     * @mbg.generated
     */
    private Integer uStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbg.generated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbg.generated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_firstName
     *
     * @return the value of user.u_firstName
     *
     * @mbg.generated
     */
    public String getuFirstname() {
        return uFirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_firstName
     *
     * @param uFirstname the value for user.u_firstName
     *
     * @mbg.generated
     */
    public void setuFirstname(String uFirstname) {
        this.uFirstname = uFirstname == null ? null : uFirstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_lastName
     *
     * @return the value of user.u_lastName
     *
     * @mbg.generated
     */
    public String getuLastname() {
        return uLastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_lastName
     *
     * @param uLastname the value for user.u_lastName
     *
     * @mbg.generated
     */
    public void setuLastname(String uLastname) {
        this.uLastname = uLastname == null ? null : uLastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_email
     *
     * @return the value of user.u_email
     *
     * @mbg.generated
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_email
     *
     * @param uEmail the value for user.u_email
     *
     * @mbg.generated
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbg.generated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbg.generated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_phone
     *
     * @return the value of user.u_phone
     *
     * @mbg.generated
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_phone
     *
     * @param uPhone the value for user.u_phone
     *
     * @mbg.generated
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone == null ? null : uPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_Status
     *
     * @return the value of user.u_Status
     *
     * @mbg.generated
     */
    public Integer getuStatus() {
        return uStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_Status
     *
     * @param uStatus the value for user.u_Status
     *
     * @mbg.generated
     */
    public void setuStatus(Integer uStatus) {
        this.uStatus = uStatus;
    }
}